# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Not_implemented.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotImplementedWindow(object):
    def setupUi(self, NotImplementedWindow):
        NotImplementedWindow.setObjectName("NotImplementedWindow")
        NotImplementedWindow.resize(202, 101)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        NotImplementedWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(NotImplementedWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 54, 12))
        self.label_2.setObjectName("label_2")
        NotImplementedWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NotImplementedWindow)
        QtCore.QMetaObject.connectSlotsByName(NotImplementedWindow)

    def retranslateUi(self, NotImplementedWindow):
        _translate = QtCore.QCoreApplication.translate
        NotImplementedWindow.setWindowTitle(_translate("NotImplementedWindow", "此功能尚未实现"))
        self.label.setText(_translate("NotImplementedWindow", "此功能尚未实现"))
        self.label_2.setText(_translate("NotImplementedWindow", "咕咕咕！"))
