# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setthingsWindow(object):
    def setupUi(self, setthingsWindow):
        setthingsWindow.setObjectName("setthingsWindow")
        setthingsWindow.resize(272, 252)
        self.centralwidget = QtWidgets.QWidget(setthingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.refillApGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.refillApGroupBox.setGeometry(QtCore.QRect(20, 10, 231, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.refillApGroupBox.setFont(font)
        self.refillApGroupBox.setObjectName("refillApGroupBox")
        self.refillApWithitemCheckBox = QtWidgets.QCheckBox(self.refillApGroupBox)
        self.refillApWithitemCheckBox.setGeometry(QtCore.QRect(20, 30, 151, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.refillApWithitemCheckBox.setFont(font)
        self.refillApWithitemCheckBox.setObjectName("refillApWithitemCheckBox")
        self.refillApWithOriginCheckBox = QtWidgets.QCheckBox(self.refillApGroupBox)
        self.refillApWithOriginCheckBox.setGeometry(QtCore.QRect(20, 50, 71, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.refillApWithOriginCheckBox.setFont(font)
        self.refillApWithOriginCheckBox.setObjectName("refillApWithOriginCheckBox")
        self.adbConectGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.adbConectGroupBox.setGeometry(QtCore.QRect(20, 90, 231, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.adbConectGroupBox.setFont(font)
        self.adbConectGroupBox.setObjectName("adbConectGroupBox")
        self.Label_3 = QtWidgets.QLabel(self.adbConectGroupBox)
        self.Label_3.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_3.setFont(font)
        self.Label_3.setObjectName("Label_3")
        self.adbServer = QtWidgets.QLineEdit(self.adbConectGroupBox)
        self.adbServer.setGeometry(QtCore.QRect(20, 50, 191, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.adbServer.setFont(font)
        self.adbServer.setText("")
        self.adbServer.setObjectName("adbServer")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(150, 200, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        setthingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(setthingsWindow)
        QtCore.QMetaObject.connectSlotsByName(setthingsWindow)

    def retranslateUi(self, setthingsWindow):
        _translate = QtCore.QCoreApplication.translate
        setthingsWindow.setWindowTitle(_translate("setthingsWindow", "设置"))
        self.refillApGroupBox.setTitle(_translate("setthingsWindow", "自动回复理智"))
        self.refillApWithitemCheckBox.setText(_translate("setthingsWindow", "自动使用回复理智道具"))
        self.refillApWithOriginCheckBox.setText(_translate("setthingsWindow", "自动碎石"))
        self.adbConectGroupBox.setTitle(_translate("setthingsWindow", "设备连接"))
        self.Label_3.setText(_translate("setthingsWindow", "ADB server："))
        self.saveButton.setText(_translate("setthingsWindow", "保存设置"))
